### ISSUE TITLE
Add built-in support for Vue

### ISSUE THREAD

**Issue by j209** [MasoniteFramework/masonite#183]
Hi 
Thanks for your greate work.
It would be greate if Masonite integrate with vue js out of the box.Just like Laravel supports the vue.

**Comment by josephmancuso** [comment]
sure. what would you like to see? next major version is coming out soon so how would you like it to work?

Just come with a package.json file?

**Comment by lazyguru** [comment]
Maybe we could handle this similar to how Laravel does with the `Preset` command? https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Console/PresetCommand.php
TL;DR:
- Command accepts a parameter for "preset" (eg bootstrap, vue, react, or none)
- If preset is "none" then remove scaffolding
- otherwise:
  - Add/update package.json with appropriate packages (exclude competing packages, eg when react exclude vue and vice versa)
  - Copy webpack.mix.js from stub directory
  - Copy example component stub into js/components/Example.js

**Comment by josephmancuso** [comment]
@lazyguru @j209 can any one of you add this feature with the presets?

**Comment by lazyguru** [comment]
I’ll work on it

**Comment by josephmancuso** [comment]
https://github.com/MasoniteFramework/masonite/pull/197
