### ISSUE TITLE
Revise the tree structure - eliminate http

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/masonite#263]
Like others, (for example, see Issue #124), I find the default tree structure puzzling. I've developed a strong dislike for the unnecessary http folder. The views also seem strangely placed. I keep getting confused by the distinction between resources and storage since the latter includes web resources such as css and js files. The bootstrap folder throws me because I think it refers to the widely used bootstrap CSS framework.

My frustration is undoubtably shaded by development experience with Ruby on Rails. Ruby on Rails apps are typically organized like this:
```
app/
    models/
    controllers/
    helpers/
    views/ aka templates
config/
    various config files including...
    routes.rb
db/
    migrate/
log/
public/ - static html, css, js, etc.
test/
```

Masonite provides a similar MVC and Active Record framework, but feels awkward to navigate as a developer.

Although I feel like a variation on the RoR structure would suit Masonite quite well, at a minimum I would suggest:

* Eliminating the http folder and moving controllers and middleware up a level. 
* Moving the templates from resources into app would also be helpful.
* Renaming bootstrap to something less confusing. Perhaps startup or engine or webserver? This seems like a folder that mostly can be ignored, but stands out due to its overloaded name.

If you are willing to consider a more aggressive restructuring, this would be my recommendation:
```
app/
    models/
    controllers/
    middleware/
    providers/
    templates/ - Or views
config/
    various config files including...
    routes.py - renamed from routes/web.py
database/
    migrations/
    seeds/
logs/
public/
tests/
```

This restructuring would consolidate the MVC (and related helpers) under the app folder. I would note that with this change, craft should create models in a models folder by default. Obviously restructuring like this would be a significant change, but it would make Masonite clearer, easier to understand, and more enjoyable to work with. The clarity would help both beginners and more experienced developers.

**Comment by josephmancuso** [comment]
It's going to be a hard to bargain to change the directory structure. It has been talked about before. We can build a way to make things less opinionated but I'd like to keep the structure of the project the same because its what I'm familiar with personally. I work on Laravel full time so when I go home I like not having to do a full paradigm shift of a new structure. I feel at home switching between work Laravel and personal Masonite projects.

There will be big changes for Masonite 3.0 in december. I will go 1 more major version for Masonite (2.4 in June) and then switch to 3.0 in decemberish release date. If we are going to do a directory restructure then there is the time. 

I'm sure there are ways to propose what you want now. I tried not hard coding a lot of the default file locations

**Comment by josephmancuso** [comment]
Thank you so much for your opinion though. I will reraise this question with the community when we get closer to 3.0. For now I'll keep the issue closed
