### ISSUE TITLE
Retrieving the full request URL

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#275]
**Is your feature request related to a problem? Please describe.**
Actually, I can get the current path with `request.path`. It would be great to add:

- `request.url ` with the full request without the query string. Ex: `http://example.com`
- `request.full_url ` with the full request with the query string. Ex: `http://example.com?q=search`

**Comment by nok** [comment]
Yes, please! It's a good idea and suggestion.

I think that a developer expect these information from a passed request. But we should't reinvent the wheel. What do you think about [furl](https://github.com/gruns/furl)?

Usage:

```python
# app/http/controllers/HelloWorldController.py

"""A HelloWorldController Module."""

from masonite.response import Response
from masonite.request import Request
from masonite.controllers import Controller


class HelloWorldController(Controller):
    """HelloWorldController Controller Class."""

    def show(self, request: Request, response: Response):
        furl = request.furl.asdict()
        return response.json(furl)
```

Response:

```
{
    "fragment": {
        "encoded": "",
        "path": {
            "encoded": "",
            "isabsolute": [],
            "isdir": true,
            "isfile": false,
            "segments": []
        },
        "query": {
            "encoded": "",
            "params": []
        },
        "separator": true
    },
    "host": "localhost",
    "host_encoded": "localhost",
    "netloc": "localhost:8000",
    "origin": "http://localhost:8000",
    "password": null,
    "path": {
        "encoded": "/hello",
        "isabsolute": true,
        "isdir": false,
        "isfile": true,
        "segments": [
            "hello"
        ]
    },
    "port": 8000,
    "query": {
        "encoded": "",
        "params": []
    },
    "scheme": "http",
    "url": "http://localhost:8000/hello",
    "username": null
}
```

Implementation:

```python
# masonite/request.py


from furl import furl
# [...]

class Request(Extendable):
    # [...]

    @property
    def furl(self) -> furl.furl:
        full_url = self.environ.get('APP_URL') + self.path  # <--- here we have to pass the full url
        return furl(full_url)
```

We can use this blueprint as a starting point.

**Comment by josephmancuso** [comment]
@nok i'm unfamiliar with furl but it looks good to me. Would you want to open a pull request for that?

**Comment by tpow** [comment]
Furl feels like overkill for my needs; I wanted to retrieve the current url and don't often need to parse it. Personally, I expected the current url to be available as request.url as with Flask. For comparison here's what flask provides on the request object:

attribute | string
--|--
path | '/π/page.html'
full_path | '/π/page.html?x=y'
script_root | '/myapplication'
base_url | 'http://www.example.com/myapplication/π/page.html'
url | 'http://www.example.com/myapplication/π/page.html?x=y'
url_root | 'http://www.example.com/myapplication/'

I'd suggest using the same names url and base_url would be nice. (Instead of full_url and url.) 

Adding url_root would also be useful since it is the foundation for the rest. Because env('APP_URL') is a configuration item, I don't find it is necessarily reliable. It also feels like maintaining something that the server already knows. I'm using something like this instead:

```python
url_root = "".join([
    self.request.environ.get("wsgi.url_scheme","http"), 
    "://", 
    self.request.environ.get("HTTP_HOST")])
```

Having request.furl would be nice, but I think request.url should also exist. (If I followed the proposed implementation, that would be request.furl.url)

**Comment by tpow** [comment]
See [PEP 3333](https://www.python.org/dev/peps/pep-3333/#url-reconstruction) which recommends the hostname part is based on SERVER_HOST and SERVER_PORT if HTTP_HOST is unavailable. The link provides an implementation to construct the full url.

**Comment by josephmancuso** [comment]
https://github.com/MasoniteFramework/masonite/pull/317
