### ISSUE TITLE
Find_or_404

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/masonite#322]
I'm not sure if this would fit better in the masonite framework or the ORM, so putting it here.

It is often the case in view controllers that you want to do a lookup in a model and either show it in a view or return a 404 not found if the record with that id can't be retrieved. This essentially replaces the find(id) method and would provide a nice shorthand.

I see that the ORM has a find_or_fail method, but at least when using `craft serve` this doesn't seem to return a 404. Instead it raises an exception. It would be helpful to have a method that returns a 404 instead.

**Comment by girardinsamuel** [comment]
It is still possible to do it quickly by creating a view but maybe a shortcut would be great, indeed !

In Django, there is a shortcut called `get_object_or_404` implemented this way
https://github.com/django/django/blob/master/django/shortcuts.py#L57
It just raises an Http404 exception when no model is found (or queryset or manager). But this works because there is a mechanism which redirects to 404 error when such an error is raised.

Here in Masonite, `find_or_fail` raises a `orator.exceptions.orm.ModelNotFound` but I don't know if it would be good to handle routing behavior inside this function... seems like bad practice to me. Maybe an other shortcut named `find_or_404` could be added that redirect to 404 when `orator.exceptions.orm.ModelNotFound` is raised ??

⚠️ But this might change with future ORM, Masonite ORM, so I'll let @josephmancuso answer here 😇.

**Comment by alexpdr** [comment]
As a temporary solution you can use the built-in model operator from orator/masonite-orm

`Model.find_or_fail()`

example:
```py

MyController(Controller):
    """Blah"""
    def show(self, request: Request, view: View) -> View:
        """Blah"""
        try:
            if user.request():
                return view.render('page', params={'data': Page.find_or_fail(request.input('page_id')})
        except ModelNotFound:
            return "Not Found", 404
```

This could in the future be added as a built-in helper method at something like:
```py
from masonite.helpers import find_or_404

MyController(Controller):
    """Blah"""
    def show(self, request: Request, view: View) -> View:
        """Blah"""
        return view.render(
            'page',
            params={
                'data': find_or_404(
                    pk=request.input('page_id'),
                    model='page'
                }
        )
```
