### ISSUE TITLE
auth.login('email', 'password') Issue

### ISSUE THREAD

**Issue by ghost** [MasoniteFramework/masonite#409]
I am getting **string argument without an encoding** error while trying to login.
```python
member = auth.guard('api').login(data.get('email'), data.get('password'))
```
What can be the possible solution for this failure?

**Comment by jpmateo022** [comment]
This is the same issue I faced in masonite-API. I think the root cause of the problem is the latest update of Python. Since masonite-API is 100% compatible with Masonite 3.0 yet, the temporary solution is to override TokenController.py

https://github.com/MasoniteFramework/api/blob/2.2/src/api/controllers/TokenController.py

Then change the response
```
return {'token': bytes(jwt.encode(payload, KEY, algorithm='HS256')).decode('utf-8')}
```

to

```
return {'token': str.encode(jwt.encode(payload, KEY, algorithm='HS256')).decode('utf-8')}
```
