### ISSUE TITLE
Issue with User Auth and Cookies

### ISSUE THREAD

**Issue by mitchellp0709** [MasoniteFramework/masonite#460]
**Describe the bug**

I am creating an API using Masonite and am using the cookie driver for authentication. I am able to log in successfully using Postman and similar tools, but in the browser I can successfully log in with my deployed API but when inspecting the request in dev tools, I see the cookies being sent in the header but they are not found in the cookies section in application. 

I figured maybe by switching to the jwt driver it would work better for building an API, but then the server wouldn't start at all and threw an error regarding importing request that seemed to come from the source code. 

While I can implement auth from scratch, I would like to use the built-in auth for my API.

Link to frontend code: https://github.com/mitchellp0709/TravelBlog-p4-Frontend
at the time of writing, the most recent commit is: ad524f663f038371c41c361c5f9bf1956c4ff9aa

Link to backend code: https://github.com/mitchellp0709/TravelBlog-P4-backend
at the time of writing, the most recent commit is: 314f9070cdaca7531f1e11bcde675ae8d5585d6e

Link to backend url: https://travel-blog-p4.herokuapp.com/
I have Cors sent to accept all requests, so you can make requests to add data and/or users

**To Reproduce**
1. Go to: /login , can use username: user1 and password: user1
2. Click on "login"
3. Should see data on the redirected page. See above for issue description.

**Expected behavior**
Once logged in, there should be data on the main page from the API, no data is being sent from the API due to the cookie issue described above. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monterey v 12.0.1
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

There was very little information in the documentation on how to set or modify cookies.

**Comment by AlexMercedCoder** [comment]
To add some more context, I am instructor with General Assembly and used Masonite as the new framework we learn with Python for building web apps. We usually do an API + SPA app, wanted to use Masonite cause it's workflow is more transferable across languages with frameworks like Rails/Laravel. 

The problem is with the default cookie driver the frontend would get the set_cookie header but the cookie doesn't get sent over and my hunch is has to do with the samesite property on the cookie not being defined and nowhere in the documentation could I find a way to customize the cookie.

We tried switch the driver to "jwt" but then that triggered an error within the Masonite source code in the AuthJWT class when it tried to import Masonite.request.Request so we couldn't even get the server to turn on with that option.

I'm assuming there isn't currently a way to turn cross-site cookies currently, but please add that in the future. I do like the framework and want to keep teaching it cause I think it lends better to learning vs other batteries includes python frameworks, but I need more clarity on what should be done differently for API building or even an API template where we just pass a flag to the new command.

**Comment by josephmancuso** [comment]
I'll take a look at this ASAP when I get off of work tonight.

**Comment by josephmancuso** [comment]
Can you join Slack to go through what exactly the flow is here? I tried to go through the replication steps above but i get a 405 on the login link from the steps.

Also @AlexMercedCoder It seems like you are trying to get the cookie from the frontend? Masonite cookies are "HTTP ONLY" meaning they cannot be gotten from the frontend but you can modify that by doing `set_cookie('cookie', http_only=False)`

**Comment by AlexMercedCoder** [comment]
We aren't trying to access the cookie on the frontend, it just isn't being set (deployed or on localhost). So we'll send the post request to the post route which uses auth.login to check the credentials, correctly verifies them and sends back the expected response with the expected set_cookie headers.

```py
def login(self):
        username = self.request.input("username")
        password = self.request.input("password")
        result= self.auth.login(username,password)
        return result
```

 but when I go into dev_tools and look at the application tab we don't see the cookie (there is no "token" cookie). The header looks as it should so my only guess from my research is the samesite property needs to be explicitly set to allow the cookie to be used cross origin (in this case the react app). At first I thought it may be just my students chrome settings but one or two people have the issue. I'll try to recreate the problem on my computer and make a video showing what I mean in the next 24 to 48 hours.

So essentially what happens is the auth middleware just tries to redirect to a login view (is that changeable?) because the cookie isn't present on subsequent requests.

I'm fine and prefer the cookie be HTTP_ONLY, as I rather not have any javascript reference it

where would I use the set_cookie function? Would that override the settings that atuh.login does under the hood?

**Comment by josephmancuso** [comment]
I thought i updated this issue. Maybe i just updated this in Slack.

The issue is that Masonite loads cookies from the browser during browser requests. As part of browser requests, they send a cookie header that has the contents for all the cookies.

On a POST request from AXIOS, the cookies header is not sent. So any cookies set on the website are ignored for AJAX requests.

So the issue here is to implement token based authentication. Masonite 3 currently doesn't have any token based authentication implementations. Masonite 4 will have support for much better API implementations once it is released and we have time to work on that part of the framework
