### ISSUE TITLE
Resolving route names

### ISSUE THREAD

**Issue by Poraksis** [MasoniteFramework/masonite#537]
**Is your feature request related to a problem? Please describe.**
There are some code duplications at 
`HTTPRoute.py => to_url` and `Router.py => compile_to_url class method`

**What do we currently have to do now?** 
These two method exactly same with each other.

**Describe the solution you'd like**
A separate method can be used to reduce code size.

**Describe alternatives you've considered**
I'm thinking that string parsing on routes not a good way, maybe it would be better 
from 
`Route.get('/dashboard/@user_id:string', 'WelcomeController@show').name('welcome')`
to something like that
`Route.get('dashboard/',{user_id : string}, 'WelcomeController.show').name('welcome')`
As you know being declarative approach is gives more performance 
- [ ] Is this a breaking change?
for framework no,but already written projects will be affect due to new syntax

**Comment by josephmancuso** [comment]
I would not be open to changing the route definitions but i'm not sure on what you want to enhance here. Are you saying the performance on routes are slow? Are you saying the time it takes for a route to compile to a url is slow? Are you saying you want to change the route definition to something more clear? Are you saying we should refactor because code is duplicated?

A few things to note:
* The compiling of a route actually happens one time when the server first boots up so the compiling of the route to regex should not effect performance.
* If you are saying the compiling of a route to a URL in a template is slow I would tend to agree with that without taking a look at the speed issues myself right now but i could see some room for improvement in theory.

Let me know what specifically you are saying is the issue here and we can open it up for discussion.

**Comment by josephmancuso** [comment]
I would be open to something like

```python
Route.get('dashboard/@user_id', 'WelcomeController.show').compiler({"user_id": "string"})
```

**Comment by josephmancuso** [comment]
but not sure how that makes this feature better
