### ISSUE TITLE
Add explicit type casting for route parameters

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite#635]
Type casting will not be achieved by route compilers as it's not its responsibility (cf Joe's comment below).

However, it would be great to be able to define how route parameters should be cast back to controller/request parameters.

## Specs
It could be done explicitly like this:

```python
Route.get("/user/@id").casts({"id": "int"})
```

or more quickly like this if the route compiler is named after a python type:
```python
Route.get("/user/@id:int").casts()
```

And then when using `request.param("id")` or resolving id from the controller `def details(self, request:Request, id)` we would get an integer.

**Comment by EpocDotFr** [comment]
I'd personally vote for the second solution as it requires less code to be written to enable casting, that would of course require route compilers to be defined properly.

Or maybe even a global config to enable casting on all routes by default?

**Comment by girardinsamuel** [comment]
Actually both solutions will be available, you will be able to use `casts()` without argument and it will try to auto cast, else you will be able to define more complex casting with first option.

> Or maybe even a global config to enable casting on all routes by default?

For now we will try to implement the simple explicit per route option and see how it's going. But we keep this in mind too 😉.

**Comment by josephmancuso** [comment]
To make one point in Sam's and my discussion transparent:

the drawbacks I see with implicit casting:
1. the `:int` thing is mainly for creating a capture group and, in my opinion, does not explicitly imply that casting will happen. Hijacking this to do casting as well can be confusing when those who expect strings get ints.
2. Its typically not the job of the framework to do implicit casting. 
3. As a developer you usually expect the response type to always be the same. So functions that return strings should always return strings. This helps with coding because if one method is returning a string, one is returning an int, one returning a float, etc. and its all kinda randomized then it makes development more unpredictable. If we do casting explicitly. then the developers expectations change obviously

3a is also why i hate when function either return a string or None. In that case it should return a string or a blank string in order to keep the same data types
