### ISSUE TITLE
how to get value from form with multiple inputs with same name and save in db.

### ISSUE THREAD

**Issue by ssestantech** [MasoniteFramework/masonite#734]
### Describe the bug

how to get value from form with multiple inputs with same name and save in db.

### Expected behaviour

how to get value from form with multiple inputs with same name and save in db.

### OS

Windows

### OS version

window 11

### Masonite Version

4.6.1

### Anything else ?

how to get value from form with multiple inputs with same name and save in db.

**Comment by girardinsamuel** [comment]
Hi ! Could you post an example of your HTML form in this issue ?

**Comment by ssestantech** [comment]
```html
<form class="multisteps-form__form" action="{{url('postform')}}" method="post" enctype="multipart/form-data">
          {{ csrf_field }}
<input type="text" name="childrenname[]">
<input type="text" name="childrenname[]">
</form>
```

**Comment by circulon** [comment]
@ssestantech 

Your issue has nothing to do with Masonite. 
Its due to the name of your fields in the form not being unique.

This same issue will happen with many languages & frameworks when parsing the HTML input fields name parameter.
  
See here for a complete explanation of your issue and how to solve getting the inputs in grouped by the  parent `childrenname` as a list

https://mattstauffer.com/blog/a-little-trick-for-grouping-fields-in-an-html-form/

Hope this helps
